---

- name: Nginx with configuration
  hosts: jenkins-user
  become: true
  vars_files: 
   - vars/all.yaml
  tasks: 
   - name: Install Nginx on Ubuntu
     apt: 
      name: nginx
      state: present

   - name: Start the nginx service, if not started
     ansible.builtin.service:
      name: nginx
      state: started

   - name: Removing a user if present
     ansible.builtin.user:
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512')}}"
      group: admin
      append: true
      shell: /bin/bash
      system: true
      createhome: yes
      home: /home/duser
      state: absent
      remove: true
      force: true

   - name: Adding a user to the machine 
     ansible.builtin.user:
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512')}}"
      group: sudo
      append: true
      shell: /bin/bash
      system: true
      createhome: yes
      home: /home/duser
      state: present

  #  - name: Add Docker Repository
  #    apt_repository:
  #       repo: deb https://download.docker.com/linux/ubuntu focal stable
  #       state: present

   - name: install dependencies
     apt:
        name: "{{item}}"
        state: present
        update_cache: yes
     loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
   - name: add GPG key
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    
   - name: add docker repository to apt
     apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

   - name: install docker
     apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
     loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io

   - name: check docker is active
     service:
      name: docker
      state: started
      enabled: yes

  
   
      


  #  - name: Configure webpage for custom input
  #    ansible.builtin.replace:
  #       command: cat /dev/null > /var/www/html/index.nginx-debian.html
  #       path: /var/www/html/index.nginx-debian.html
  #       regexps: '$^'
  #       replace: <h1>hello this file in edited from ansible<h1>

  #  - name: Replace file contents with required
  #    shell:  
  #     cmd: echo "This is my new website" > /var/www/html/index.nginx-debian.html

  #  - name: restart nginx service
  #    ansible.builtin.service:
  #      name: nginx
  #      state: restarted
