---

- name: Nginx with configuration
  hosts: jenkins-user
  become: true
  vars_files: 
   - vars/all.yaml
  tasks: 
   - name: Install Nginx on Ubuntu
     apt: 
      name: nginx
      state: present

   - name: Start the nginx service, if not started
     ansible.builtin.service:
      name: nginx
      state: started

   - name: Adding a user to the machine 
     ansible.builtin.user:
      name: "{{ username }}"
      password: nginx123#
      group: sudo
      createhome: yes
      home: /home/dinu
   
      


  #  - name: Configure webpage for custom input
  #    ansible.builtin.replace:
  #       command: cat /dev/null > /var/www/html/index.nginx-debian.html
  #       path: /var/www/html/index.nginx-debian.html
  #       regexps: '$^'
  #       replace: <h1>hello this file in edited from ansible<h1>

  #  - name: Replace file contents with required
  #    shell:  
  #     cmd: echo "This is my new website" > /var/www/html/index.nginx-debian.html

  #  - name: restart nginx service
  #    ansible.builtin.service:
  #      name: nginx
  #      state: restarted
