---

- name: Nginx with configuration
  hosts: jenkins-user
  become: true
  tasks: 
   - name: Install Nginx on Ubuntu
     apt: 
      name: nginx
      state: present

   - name: Start the nginx service, if not started
     ansible.builtin.service:
      name: nginx
      state: started
